### ISSUE TITLE
实际的命令比设置的参数多，怎么确定参数呢？

### ISSUE THREAD

**Issue by fetchingly** [eguid/FFCH4J#1]
我安装的ffmpeg的版本，推流的命令不成功，改了命令就可以了

**Comment by eguid** [comment]
嗯，命令需要根据各个版本ffmpeg的来定，用下面两个API就可以执行原生ffmpeg命令：
//执行原生ffmpeg命令（不包含ffmpeg的执行路径，该路径会从配置文件中自动读取）
manager.start("test1", "ffmpeg -i input_file -vcodec copy -an output_file_video");
//包含完整ffmpeg执行路径的命令
manager.start("test2,","d:/ffmpeg/ffmpeg -i input_file -vcodec copy -an output_file_video",true);
