### ISSUE TITLE
请问106.14.182.20这个服务器是用什么搭建的？

### ISSUE THREAD

**Issue by pnoker** [eguid/FFCH4J#15]
您好，请问106.14.182.20这台服务使用什么搭建的，是Nginx+RTSP Module搭建的吗？

**Comment by eguid** [comment]
rtsp服务可以，吃惊？！nginx现在已经有rtsp插件了吗

**Comment by pnoker** [comment]
嗯呢，是可以的，我就是用Nginx搭建的RTMP服务器。

**Comment by pnoker** [comment]
我最近在我的个人项目iot-dc3中使用你提供的代码，发现一些问题，我目前使用的RTSP流无法执行命令。

**Comment by pnoker** [comment]
rtsp://221.180.150.148:554/66000000000000000010eurie2304384_5?stype=live&streamid=2&isfixedrtsp=1

**Comment by pnoker** [comment]
您好，方便加个联系方式吗？
