### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by dongfangding** [eguid/FFCH4J#17]
在使用中碰到一些问题，有些查了下源码，有些大致看了下，有几个问题想请教下；
1. 创建任务的时候，有时候我会希望创建成功会做一些事情，源码如下
```java
String start = commandManager.start(startId.toString(), CommandBuidlerFactory.createBuidler().add(zhiboConfig.getCmd()));
log.info("执行任务返回结果{}: {}", null == start ? "失败" : "成功", start);
if (null != start) {
    ZhiBoRunningStore.setZhiBo(zhiboConfig, ZhiBoState.State.running);
}

// 但对应的tart源码却如下
public String start(String id, String command, boolean hasPath) {
		if (isInit(true)) {
			System.err.println("执行失败，未进行初始化或初始化失败！");
			return null;
		}
		if (id != null && command != null) {
			CommandTasker tasker = taskHandler.process(id, hasPath ? command : config.getPath() + command);
			if (tasker != null) {
				int ret = taskDao.add(tasker);
				if (ret > 0) {
					return tasker.getId();
				} else {
					// 持久化信息失败，停止处理
					taskHandler.stop(tasker.getProcess(), tasker.getThread());
					if (config.isDebug())
						System.err.println("持久化失败，停止任务！");
				}
			}
		}
		return null;
	}
```
由于`taskDao`的存在，第一次成功会把数据放进去，假如之后任务出现了问题，非应用挂掉，我想重启这个任务，在这条数据没有清除的情况下，我可能更希望任务存在直接返回任务id就好？
因为目前有没有启动成功我也只能通过返回的这个字符串来判断了，而这个字符串本身却并不具备这个含义；

2. 关于保活线程如下的代码疑问
```java
	@Override
	public void run() {
		for(;stop_index==0;) {
			while(queue==null) {
				try {
					condition.await();
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
			String id=null;
			CommandTasker task=null;
			
			try {
				while(queue.peek() != null) {
					System.err.println("准备重启任务："+queue);
					id=queue.poll();
					task=taskDao.get(id);
					//重启任务
					ExecUtil.restart(task);
				}
			}catch(IOException e) {
				System.err.println(id+" 任务重启失败，详情："+task);
				//重启任务失败
				err_index++;
			}catch(Exception e) {
				
			}
		}
	}
```
开启保活线程的情况下，`CommandManagerImpl`每次没创建都会创建一个保活线程，而保活线程是采用无线循环的方式来循环，在实际使用过程中每个创建的`CommandManagerImpl`都会让一个cpu的使用率达到100%，看起来`CommandManagerImpl`应该是当个全局管理类来使用，但依然会存在让一个cpu的使用率过高的问题，我觉得是否可以再`OutHandler`将重启任务交给保活线程的时候再唤醒，当保活线程队列中没任务的时候继续等待；

3. 关于OutHandler能否抽象出来？目前的实现固定了也无法自己实现，而原来的实现在进程没有输出之后默默的关闭了自己的线程，却没有告知其它任何组件当前进程无消息输出了，这个状态对于有些情况来说很重要，因为目前只有异常或丢包，但还有一种就是本身没有故障，只是源没有消息了
```
/**
	 * 执行输出线程
	 */
	@Override
	public void run() {
		String msg = null;
		try {
			if (CommandManager.config.isDebug()) {
				System.out.println(id + "开始推流！");
			}
			while (desstatus && (msg = br.readLine()) != null) {
				ohm.parse(id, msg);
				if (ohm.isbroken()) {
					System.err.println("检测到中断，提交重启任务给保活处理器");
					//如果发生异常中断，立即进行保活
					//把中断的任务交给保活处理器进行进一步处理
					KeepAliveHandler.add(id);
					condition.signal();
				}
			}
		} catch (IOException e) {
			System.out.println("发生内部异常错误，自动关闭[" + this.getId() + "]线程");
			destroy();
		} finally {
			if (this.isAlive()) {
				destroy();
			}
		}
	}
```

以上问题可能有自己没看明白的地方，还请不吝赐教；

**Comment by eguid** [comment]
首先感谢你的的建议，另外欢迎大家参与这个项目，贡献代码并一起完善这个项目。
对于你的几个问题分别来回答：
1、创建任务返回的字符串默认就是任务ID，而任务创建不成功，会返回null；而你讲的想重启一个任务，可以通过先stop(id)，然后start()来实现，我会在下个版本中增加一个重启的语法糖来方便任务重启
2、感谢反馈CommandManagerImpl的cpu占用率100%问题，已经记录下来，下个版本会优先修复这个bug；
2.1、为什么没有用OutHandler的线程来做保活，而是另开了一个保活线程这个问题。
是这样的，outhandler会读取一个任务进程的字符io流，一般情况下它会在读取流，其他情况都是阻塞状态，没有空闲时间去做其他事情，比如保活；
3、outhandler是可以自行实现这个接口的具体实现并且通过commandManagerImpl注入到程序中使用，所以你可以轻易的定制outhandler的具体实现，程序中每个接口都提供了一个默认的简单实现，都可以都过实现那些接口并注入来实现功能得定制，可能文档里没有讲到，后面我会在文档里补充这部分内容

**Comment by dongfangding** [comment]
感谢抽出时间回复；
对于第三个问题，我理解下来你可能以为我说的是`cc.eguid.commandManager.handler.OutHandlerMethod`，而我实际上问的是`cc.eguid.commandManager.handler.OutHandler`，我这个问题的困扰是`OutHandler是一个标准的class，被创建用来解析`Process`的`ErrorStream`，而在这之后才有了`OutHandlerMethod`来对结果进行`parse`，所以我的疑问是假如我的需求是输入流没有结果了，我可能会做一些处理，因为这是`Process`源头上就出现了问题；但其实`OutHandlerMethod`并没有与这个结果进行通信；所以这个接口我无法拿到这个结果；当然这只是我碰到的问题，不确定实际上这是不是合理的。

**Comment by eguid** [comment]
这个问题确实没有考虑到。
上个版本中是没有OutHandlerMethod的，现在这个版本为了方便保活增加了OutHandlerMethod并且去掉了OutHandler接口，可能下个版本会把这块回退到上个版本，依然使用OutHandler接口来实现

**Comment by dongfangding** [comment]
老哥，不好意思，我又来了，尴尬；
关于之前我说过由于保活线程的问题，每次创建一个`CommandManagerImpl`都会创建一个保活线程（配置已开启创建的情况下），所以看起来`CommandManagerImpl`像是一个全局管理类；现在对于这一块我有一些新的疑问产生，保活线程是根据`OutHandlerMethod`接口的`isbroken`方法返回的true来判断任务已经中断来把任务再次加入到队列中，在默认的实现中`DefaultOutHandlerMethod`的`isBroken`属性并没有考虑线程安全的问题，所以如果真的按照我之前的想法当做全局类来使用，可能会导致该属性在不同线程间的使用造成混乱；但是如果不能按照`singleton`来使用，我只能设置为`prototype`，（或者自己重新实现线程安全，先不考虑这个），所以必然的我的`CommandManager`也不能`singleton`了，那么问题来了，`TaskDao`我可以设置为`singleton`注入进去，但保活线程却不能由我来控制，这个问题就很严重了，每个实例都会有一个保活线程；所以我觉得这一块是不是应该好好梳理下，关于这个类的流程以及辅助类之间的使用有哪些注意事项，是否能给个比较合理的建议使用方式？

**Comment by dongfangding** [comment]
补充一点，接口`TaskDao`被设计允许自定义，但创建`CommandManagerImpl`的逻辑与自定义`TaskDao`还有包括线程之间的判断似乎有点问题,我自定义实现了`TaskDao`之后保活线程却无法再被创建了；代码如下:
```java
if (this.taskDao == null) {
	this.taskDao = new TaskDaoImpl(size);
	//初始化保活线程
	if(iskeepalive) {
		keepAliveHandler = new KeepAliveHandler(taskDao);
		keepAliveHandler.start();
	}
}
```

**Comment by eguid** [comment]
建议单例使用，如果有好的点子，欢迎贡献代码，该项目短期内没有更新计划

**Comment by dongfangding** [comment]
感谢；


------------------ 原始邮件 ------------------
发件人: "eguid"<notifications@github.com>;
发送时间: 2019年5月10日(星期五) 下午5:13
收件人: "eguid/FFCH4J"<FFCH4J@noreply.github.com>;
抄送: "☺☺☺☺☺☺☺☺☺☺"<1041765757@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [eguid/FFCH4J] 代码问题 (#17)




建议单例使用，如果有好的点子，欢迎贡献代码，该项目短期内没有更新计划

**Comment by lineezhang** [comment]
确实上面这个@dongfangding c说到点子上了，那个OutHandlerMethod方法里面的那个boolean 没有考虑到线程安全。那么单例的用法就无从说起。。
