### ISSUE TITLE
新版本

### ISSUE THREAD

**Issue by zhengweis** [eguid/FFCH4J#2]
老哥 什么时候出新版本，支持管理界面

**Comment by eguid** [comment]
新版本很快就出，管理界面还要等等（先优先解决所有已知bug）。
之前很多同学反馈长时间运行的FFmpeg命令（比如rtsp转rtmp转流），如果其中一端网络断开，就会导致任务进程中断，所以下个版本会解决这个问题，并且把命令分为两类：瞬时命令和长时间任务命令，长时间运行的命令会增加一个中断重启和错误反馈功能，以保证任务进程的长期可靠运行。
